_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  type: TSMSDataset
  file: /home/dan/zmz/timeserise/snn_tcn_gru/SeqSNN/exp/data/pems-bay.h5
  window: 12
  horizon: 48
  train_ratio: 0.7
  test_ratio: 0.2
  raw_label: False
  normalize: 2

runner:
  type: ts
  task: regression
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0
  loss_fn: mse
#  denormalize: True
  metrics: [mae, rmse, r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 500
  early_stop: 30
  batch_size: 64 #64
  aggregate: True  #True

network:
  type: SNN_TCN2D
  kernel_size: 3
  num_levels: 3
  channel: 16
  dilation: 2
  dropout: 0.
  num_steps: 4
  hidden_size: 64
  pe_type: none
  pe_mode: add
  num_pe_neuron: 40
  neuron_pe_scale: 10000.0
#  gru2d_params:
#    hidden_size: 32
#    layers: 1
#    num_steps: 12
#    grad_slope: 25.0

runtime:
  seed: 42
  output_dir: ../outputs/neuron_horizon=48_pems-bay
