_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  type: TSMSDataset
  file: /home/dan/zmz/timeserise/SeqSNN/SeqSNN-main/exp/data/electricity.txt
  window: 168
  horizon: 24
  train_ratio: 0.7
  test_ratio: 0.2
  raw_label: False
  normalize: 3

runner:
  type: ts
  task: regression
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse, rmse,  mae, corr]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  batch_size: 24
  aggregate: Ture

network:
  type: SNN_TCN2D
  kernel_size: 16
  num_levels: 3
  channel: 16
  dilation: 2
  dropout: 0.
  num_steps: 4
  hidden_size: 64
  stride: 1
  encoder_type: conv
  pe_type: none
  pe_mode: add
  num_pe_neuron: 40
  neuron_pe_scale: 1000.0

runtime: 
  seed: 40
  output_dir: ./outputs/spiketcn2d_helectricity-6_promax

