_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  type: TSMSDataset
  file: /home/dan/zmz/timeserise/SeqSNN/SeqSNN-main/exp/data/metr-la.h5
  window: 168
  horizon: 24
  train_ratio: 0.7
  test_ratio: 0.1
  raw_label : False

runner:
  type: ts
  task: regression
  optimizer: Adam
  lr: 0.005
  weight_decay: 0.0
  loss_fn: mse
  metrics: [mae, rmse, r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  batch_size: 64
  aggregate: False

network:
  type: SNN_TCN2D
  kernel_size: 3
  num_levels: 3
  channel: 16
  dilation: 2
  dropout: 0.
  num_steps: 4
  hidden_size: 64
  encoder_type: conv
  pe_type: neuron
  pe_mode: add
  num_pe_neuron: 40
  neuron_pe_scale: 10000.0

runtime: 
  seed: 42
  output_dir: ./outputs/spiketcn2d_horizon=24_metr-la