_base_:
- ../model/spikegru.yml
- ../dataset/solar.yml
_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  raw_label: False
  window: 12
  horizon: 24

runner:
  type: vsts
  batch_size: 44
  aggregate: False
  out_size: 24
  denormalize: True
  task: regression
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [corr, r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  denormalize: True
  valid_variates: 137

network:
  type: ISNNGRU2d
  num_steps: 4
  layers: 1
  hidden_size: 1
  encoder_type: conv

runtime:
  seed: 42
  output_dir: ./outputs/snn2dvsts_horizon=96_solar